name: Build App

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build
    permissions:
      contents: read
      actions: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: linux
            mxd-platform: linux-musl
            mxd-arch: x86_64
          - os: windows-latest
            target: win
            mxd-platform: windows
            mxd-arch: x86_64
          - os: macos-latest
            target: mac
            mxd-platform: darwin
            mxd-arch: aarch64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Download mxd
        run: bun run ./scripts/download-mxd.ts
        env:
          MXD_PLATFORM: ${{ matrix.mxd-platform }}
          MXD_ARCH: ${{ matrix.mxd-arch }}
          MXD_COMMIT: ${{ vars.MXD_COMMIT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the app
        run: bun run build ${{ matrix.target }}
      - name: Read package.json
        id: read_package_json
        run: echo "::set-output name=package_json::$(cat package.json)"
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        if: github.event_name == 'release' && github.event.action == 'created'
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/LLMOne-${{ matrix.target }}-${{ fromJson(steps.read_package_json.outputs.package_json).version }}.${{ matrix.target == 'linux' && 'AppImage' || matrix.target == 'mac' && 'dmg' || 'zip' }}
          asset_name: LLMOne-${{ matrix.target }}-${{ fromJson(steps.read_package_json.outputs.package_json).version }}.${{ matrix.target == 'linux' && 'AppImage' || matrix.target == 'mac' && 'dmg' || 'zip' }}
          asset_content_type: ${{ matrix.target == 'linux' && 'application/vnd.appimage' || matrix.target == 'mac' && 'application/x-apple-diskimage' || 'application/zip' }}
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: LLMOne-${{ matrix.target }}-${{ fromJson(steps.read_package_json.outputs.package_json).version }}.zip
          path: ./release/LLMOne-${{ matrix.target }}-${{ fromJson(steps.read_package_json.outputs.package_json).version }}.${{ matrix.target == 'linux' && 'AppImage' || matrix.target == 'mac' && 'dmg' || 'zip' }}
